[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
green = "0x87af87"
red = "0xd78787"

[colors.normal]
cyan = "0x8cd0d3"
green = "0x87af87"
red = "0xd78787"

[colors.primary]
background = "0x383838"
foreground = "0xdcdccc"

[font]
size = 11.0

[window]
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2
